// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_tech_task/test/presentation/pages/bookmarked_details_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_bloc/flutter_bloc.dart' as _i5;
import 'package:flutter_tech_task/data/models/post.dart' as _i4;
import 'package:flutter_tech_task/presentation/cubits/bookmark_cubit/bookmark_cubit.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBookmarkState_0 extends _i1.SmartFake implements _i2.BookmarkState {
  _FakeBookmarkState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookmarkCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookmarkCubit extends _i1.Mock implements _i2.BookmarkCubit {
  MockBookmarkCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BookmarkState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBookmarkState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.BookmarkState);

  @override
  _i3.Stream<_i2.BookmarkState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<_i2.BookmarkState>.empty(),
      ) as _i3.Stream<_i2.BookmarkState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> toggleBookmark(_i4.Post? post) => (super.noSuchMethod(
        Invocation.method(
          #toggleBookmark,
          [post],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool isBookmarked(int? postId) => (super.noSuchMethod(
        Invocation.method(
          #isBookmarked,
          [postId],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<_i4.Post> getBookmarkedPosts() => (super.noSuchMethod(
        Invocation.method(
          #getBookmarkedPosts,
          [],
        ),
        returnValue: <_i4.Post>[],
      ) as List<_i4.Post>);

  @override
  void emit(_i2.BookmarkState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i5.Change<_i2.BookmarkState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
